version: 1

url: https://forms.office.com/Pages/ResponsePage.aspx?id=gSDm-9gGHUi6oDQUnP76X4lpmu-KMtlNiBNPMrHQ_F5UOTM3VUFJS0FESE5aU1hRNkZEVFIzNUI4NiQlQCN0PWcu
answers:
  - generator: constant
    options:
     value: 'Arya Shah'

  - generator: constant
    options:
      value:'Employee'

  - generator: constant
    options:
      value: 'Yes'
      
  - generator: constant
    options:
      value: 'No'
      
  - generator: constant
    options:
      value: 'No'
      
  - generator: constant
    options:
      value: 'Yes, Shown to Security'
