version: 1

url: https://forms.office.com/Pages/ResponsePage.aspx?id=XYP-cpVeEkWK4KezivJfyMh6mdFa-OFBkHsyBFa3fSVUODFSWUZGUU1TSzFGWVFFOE1MSjI1NkhOViQlQCN0PWcu
answers:
  - generator: constant
    options:
     value: 'Arya Shah'

  - generator: constant
    options:
      value:'Employee'

  - generator: constant
    options:
      value: 'Yes'
      
  - generator: constant
    options:
      value: 'No'
      
  - generator: constant
    options:
      value: 'No'
      
  - generator: constant
    options:
      value: 'Yes, Shown to Security'
